language:go
go:
  - 1.11.x

install:
  - go get Github.com/gohugoio/hugo

script:
  - mkdir -p themes/beautifulhugo && git clone https://Github.com/halogenica/beautifulhugo.git themes/beautifulhugo

  - hugo --theme beautifulhugo

depoly:
  provider: pages
  skip_cleanup: true
  Github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
